### PR TITLE
Fix: Assets cannot be rendered with chained extension

### PR DESCRIPTION
**Pull request by aiotter**
## Describe the bug
You cannot get "hydration.client.tsx" rendered with a `_config.ts` below.
```ts
site.loadPages([".tsx"], moduleLoader, tsxEngine)
  .loadAssets([".client.tsx"], clientSideScriptLoader)
  .process([".client.tsx"], (page) => page.dest.ext = ".js")
```

## Background
The problem on code which directory causes the bug is that pages are always preferred over assets.
https://github.com/lumeland/lume/blob/f02e6832db31cc55f6da96fcab39213e50c17411/core/source.ts#L212-L213

1d67763c198972c202aed359f1f21e9f0f076aca fixes this, however, another problem occurrs.
In the current implementation, `Site.renderer.renderPages()` renders everything with `Site.renderer.engines.render()`. So when you have a matching extension in the engines, the file will be rendered by the corresponding engine even if the file is actually an asset, not a page.
https://github.com/lumeland/lume/blob/f02e6832db31cc55f6da96fcab39213e50c17411/core/renderer.ts#L88-L97 

To prevent this, we have to use `if` clause not to execute `engines.render()`for assets. However, we have no knowledge about the file in problem is an asset or a page on the context of `Site.renderer`.
So I implemented `Site.assets` array to store assets separately from `Site.pages`. To make it more natural, I also implemented a new class `Asset`, which is an analogue of `Page`.

### CODE REVIEW

**Comment by aiotter** [comment]
Sorry I forgot to run the test in my local environment.
I'll fix it tomorrow (maybe), but can you take a glance at my code beforehand?
If you don't want this kind of implementation, I'll close the PR and follow your way.

**Comment by oscarotero** [comment]
Hi, @aiotter 
Thanks for this. I understand the problem and clearly there's something that needs to be fixed.
I have to think more deeply about this solution, because I'm not convinced about separating assets and pages as different things.
There are cases in which a page is used to generate an asset (example: `styles.css.njk` is a nunjucks file that output a css file). The only difference of pages and assets is that pages use to output html code, and assets don't, so the pages output include the html extension (`page.njk -> page/index.html`) and assets maintain the extension of the input file (`styles.css -> styles.css`).

To handle simple and chained extensions, there's the [`Extension` class](https://github.com/lumeland/lume/blob/master/core/extensions.ts). The problem here is that multiple Extensions instances are used (one for pages, other for assets etc), so they don't know each other. Maybe if we have a single `Extensions` instance that contain everything, the problem could be fixed (I'm thinking out loud). I imagine something like this:

```ts
const info = extensions.get(".tsx");
info.pageLoader; // Return the page loader for this extension or undefined
info.assetLoader; // Return the asset loader for this extension or undefined
info.dataLoader; // Return the data loader for this extension or undefined
info.processors; // Return the processors for this extension
info.preprocessors; // Return the preprocessors for this extension

const info2 = extensions.get(".client.tsx");
// info2 would have different values as info.
```

FYI, I have this with the Lume architecture, that includes all properties of the `Site` instance and their relationship: https://miro.com/app/board/uXjVOb60Gx8=/

**Comment by aiotter** [comment]
> I'm not convinced about separating assets and pages as different things

I know this can be your general idea, because there is only one class `Page` for representing generated resource.
However, the API of Lume is different. You have two different API for registering pages and assets. `Site.loadPages` with `PageLoader` and `Site.loadAssets` with `AssetLoader`. This confused me.

Don't you think it's better to make `Site.loadPages` take another argument representing to which extension the file will be rendered, like `site.loadPages([".client.tsx"], clientSideScriptLoader, , ".js")`?
You can leave `Site.loatAssets` to be aliased to `Site.loadPages` with the last argument set to `null`.
This makes clear for everyone that the asset is a special type of page, and extend flexibility of Lume by allowing users to generate page assets other than HTML using `Engine`s. For example, you can even create PHP with liquid engine. And this change of UI doesn't break the backward compatibility at all.

**Comment by oscarotero** [comment]
Yes, I like it.
The API is different because I think it's more clear and easy for users to have a `loadPages` / `loadAssets` than a unique `loadAssets` with a lot of options. But I like the idea of making aliases. In fact the `filter` function is an alias of `helper`. Let me try some things and I'll let you know.

**Comment by oscarotero** [comment]
Hi, again. I just commit the first version of the new `ResourceLoader` class that merges `PageLoader` and `AssetLoader`.
Take a look at #166 and let me know if it works for you.

**Comment by oscarotero** [comment]
This PR is no needed, because this issue was fixed in #166, so I close this.
Thanks!

**Pull request closed without merging**
