### PR TITLE
Add `mdx` filter

### PR DESCRIPTION
**Pull request by kwaa**
## Description

This PR adds an `mdx` Filter to the MDX plugin.

### Check List

- [x] Have you read the
      [CODE OF CONDUCT](https://github.com/lumeland/lume/blob/master/CODE_OF_CONDUCT.md)
- [x] Have you read the document
      [CONTRIBUTING](https://github.com/lumeland/lume/blob/master/CONTRIBUTING.md)
  - [x] One pull request per feature. If you want to do more than one thing,
        send multiple pull request.
  - [x] Write tests.
  - [x] Run deno `fmt` to fix the code format before commit.
  - [x] Document any change in the `CHANGELOG.md`.

### CODE REVIEW

**Comment by oscarotero** [comment]
Sorry for the late response. It looks great!
Can you include a test example?

You can take the vto test as example: https://github.com/lumeland/lume/blob/main/tests/assets/vento/vto-filter.page.js

**Comment by kwaa** [comment]
> Can you include a test example?

I added an example.

**Comment by oscarotero** [comment]
@kwaa In this case it's `undefined` because it's not a real file.

**Comment by kwaa** [comment]
> In this case it's `undefined` because it's not a real file.

If use `undefined`, it will report error:

```bash
Build a mdx site => ./tests/mdx.test.ts:5:6
error: Error: Error rendering the page: /mdx-filter.page.ts
            throw new Error(`Error rendering the page: ${page.sourcePath}`, {
                  ^
    ...
Caused by: TypeError: Path must be a string. Received undefined
    ...
```

**Comment by oscarotero** [comment]
Hmm, okay. It must be here: https://github.com/lumeland/lume/blob/main/plugins/mdx.ts#L73
Not sure if baseUrl is mandatory for mdx. If it is, maybe it can changed to:
```js
const baseUrl = toFileUrl(join(this.baseUrl, filename || "")).href;
```

**Comment by kwaa** [comment]
> Not sure if baseUrl is mandatory for mdx. If it is, maybe it can changed to:
> 
> ```js
> const baseUrl = toFileUrl(join(this.baseUrl, filename || "")).href;
> ```

Changing to this works fine:

```diff
- const baseUrl = toFileUrl(join(this.baseUrl, filename || "")).href;
+ const baseUrl = toFileUrl(join(this.baseUrl, filename || "/")).href;
```

Using an empty string will cause the JSX import to fail.

**Comment by oscarotero** [comment]
Great. Good work, thanks you!!

**Pull request merged**
