### PR TITLE
Lume 2

### PR DESCRIPTION
**Pull request by oscarotero**
This is a Pull Request to track all changes for Lume 2.0

- All changes are documented in [MIGRATION.md](https://github.com/lumeland/lume/blob/v2/MIGRATION.md).
- The release of Lume 2 is planned for when Deno v2 comes out

### CODE REVIEW

**Comment by ngdangtu-vn** [comment]
May I suggest to rename the core plugin `search` to `query`? It could be useful in if people want to searching for help. I've posted about this case in discord bot ai

**Comment by ngdangtu-vn** [comment]
May I suggest to rename the core plugin `search` to `query`? It could be useful in if people want to searching for help. I've posted about this case in discord bot ai.

**Comment by ngdangtu-vn** [comment]
Speaking of array value, the other properties could use it as well...

```js
// 1. string query
`genre=comedy`

// 1.a value prefix
`genre=!comedy` // (!) is prefix of negative not
`genre=^c` // (^) is prefix of beginning
`genre=*c` // (*) is prefix of middle
`genre=$y` // ($) is prefix of ending

// 2. array array
`genre=[comedy]`
`genre=[comedy,romantic]` // (,) means and
`genre=[comedy|romantic]` // (|) means or

// 2.a array item prefix
`genre=[!comedy,romantic]` // (!) is prefix of negative not
`genre=[^c,romantic]` // (^) is prefix of beginning
`genre=[$y,romantic]` // ($) is prefix of ending

// 3. math query
`genre=comedy` // is

// 3.a for number type only
`episode==69` // equal
`episode>69` // greater
`episode<69` // lesser
`episode>=69` // greater or equal
`episode<=69` // lesser or equal

// 3.b for array type only
`genre==[69]` // array length has 69 items
`genre>[69]` // length is greater
`genre<[69]` // length is lesser

// 4. combination query
`genre=[comedy,romantic]&theme=superhero` // (&) means and
`genre=[comedy,romantic]|theme=superhero` // (|) means or
`genre=[comedy,romantic]|(theme=superhero&episode=2)` // (parenthesis) group
```

Basically, we have 6 operators in total (relation between key & value):    
(all num only can be called math operators as well)

- `=` is : () if num is used, it will be treat like string
- `==` equal : (compare op)
- `>` greater : (compare op) 
- `<` lesser : (compare op) 
- `>=` greater or equal : (compare op) 
- `<=` lesser or equal : (compare op) 

The syntax also uses 5 prefixes (patterns) (value trait):

- `` no pattern, looking for the value
- `!` negative pattern, anything but the value
- `^` beginning pattern of looking for str starts from the value
- `$` ending pattern of looking for str finishes with the value
- `*` include pattern of looking for str contains the value

There are 2 types of wrappers:

- `[]` array value has multiple combination
  - with `=` and 5 patterns, it looks for pages with those patterns (values' relation depend on dividers, see below)
  - with compare op and 1 numeric value only, it looks for pages has the valid array length. `genre==[69]` genre property must have 69 items, for ex.
- `()` group is high priority (no nesting, it's too complicated)

And 3 dividers of wrapper (relation in wrapper):

- `,` and (for array)
- `&` and (for group)
- `|` or (for all)


Even though I'm the culprit did this proposal. I can sadly say, I don't know how to implement this shit :'( Even if you approve, it may take long time to deal with this logic. But at least, it doesn't as confuse as OR condition in the doc right?

**Comment by oscarotero** [comment]
I my opinion, your proposal is too complex, and currently, there's an `or` operator (for example `genre=comedy|romantic`).
For now, I won't make changes because the current API is enough for the 99% cases and anyone needs something more powerful, it's possible to create a tailored solution.

**Pull request closed without merging**
