### PR TITLE
Merge pageLoader and assetsLoader into resourceLoader

### PR DESCRIPTION
**Pull request by oscarotero**
Related to #165

### CODE REVIEW

**Comment by aiotter** [comment]
Hi, I'm surprised to your quick rewrite.
I have a suggestion for this code. Can I open another PR against `resource-loader` branch so that you'll see the diff easier?

**Comment by oscarotero** [comment]
Yes, sure!
Thanks

**Comment by aiotter** [comment]
Ok, I'll send a new PR later.

btw, I have run `lume/ci.ts` in this PR and saw something really weird happened.

```ts
// _config.ts

import lume from "lume/mod.ts";
import * as Nano from "https://deno.land/x/nano_jsx@v0.0.26/mod.ts";
import moduleLoader from "lume/core/loaders/module.ts";
import { Data } from "lume/core.ts";

export class NanoJsxEngine {
  helpers: Record<string, Helper> = {};

  deleteCache() {}

  addHelper(name: string, fn: Helper) {
    this.helpers[name] = fn;
  }

  render(content: Nano.Component | Nano.FC, data: Data): Promise<string> {
    return Promise.resolve(this.renderSync(content, data));
  }

  renderSync(content: Nano.Component | Nano.FC, data: Data): string {
    const { children, ...props } = data;
    if (Array.isArray(children)) {
      return Nano.renderSSR(() => Nano.h(content, props, ...children));
    } else {
      return Nano.renderSSR(() => Nano.h(content, props, children));
    }
  }
}

const nanoEngine = new NanoJsxEngine();

const site = lume();
site.loadPages([".tsx"], moduleLoader, nanoEngine);
site.loadAssets([".client.tsx"]);
site.process([".client.tsx"], (page) => page.dest.ext = ".js");

export default site;
```

```tsx
// test.client.tsx

/** @jsx Nano.h */
/** @jsxFrag Nano.Fragment */

import * as Nano from 'https://deno.land/x/nano_jsx/mod.ts'

console.log(true);

```

```tsx
// _site/test.js (generated)
// SOMETHING HAPPENED!!!

</** @jsx Nano.h */
/** @jsxFrag Nano.Fragment */

import * as Nano from 'https://deno.land/x/nano_jsx/mod.ts'

console.log(true);
 paginate="function* paginate(results, userOptions = {}) {
        const options = merge(defaults1, userOptions);
        const totalResults = results.length;
        const totalPages = Math.ceil(results.length / options.size);
        let page1 = 1;
        let data = createPageData(page1);
        for (const result of results){
            data.results.push(result);
            if (data.results.length  search="[object Object]" tags="" content="/** @jsx Nano.h */
/** @jsxFrag Nano.Fragment */

import * as Nano from &apos;https://deno.land/x/nano_jsx/mod.ts&apos;

console.log(true);
" url="/test.client.tsx">= options.size) {
                yield data;
                data = createPageData(++page1);
            }
        }
        if (data.results.length) {
            yield data;
        }
        function createPageData(page) {
            return {
                url: options.url(page),
                results: [],
                pagination: {
                    page,
                    totalPages,
                    totalResults,
                    previous: page > 1 ? options.url(page - 1) : null,
                    next: totalPages > page ? options.url(page + 1) : null
                }
            };
        }
    }"><//** @jsx Nano.h */
/** @jsxFrag Nano.Fragment */

import * as Nano from 'https://deno.land/x/nano_jsx/mod.ts'

console.log(true);
>
```

Commenting out `site.loadPages([".tsx"], moduleLoader, nanoEngine);` solves the issue. Something is wrong with this branch.

**Comment by oscarotero** [comment]
@aiotter Ok, this is because Lume render all pages (.tsx and .client.tsx) as .tsx pages (due the same issue as we had with pages and assets).

I've fixed it including the engine in the `Resource` interface (now renamed to `Extension`) https://github.com/lumeland/lume/blob/5eeb2d72199fa653f511d3885f4117d4dbb1c903/core.ts#L68-L72

This means that now the .tsx extension will have a loader and a engine different to .client.tsx.

The more I think about it, the more I think to extend this interface, to contain everything related with a extension (not only the page loader and engine, but also data loader, component loader, processors/preprocessors, etc). And maybe rename it to `Format`.

**Comment by aiotter** [comment]
Now it works!

> The more I think about it, the more I think to extend this interface, to contain everything related with a extension (not only the page loader and engine, but also data loader, component loader, processors/preprocessors, etc). And maybe rename it to Format.

Nice! I feel it very natural and clear. And that's near to what I wanted to suggest. (So no need of another PR anymore)

I don't like that `ResourceType`. Assets and pages can be treated as the same. The only difference is extension conversion (pages can lack the Engine, so the absence of Engine is not specific to assets).
So how about this one?

```ts
interface Format {
  extension: {from: string[], to: string},
  loader: ResourceLoader,
  engine?: Engine,
}
```


Or even better, you can include extension conversion in `Engine`. In this case `Engine` may be better to be renamed to `Modifier`.
`Modifier` is responsible for modifying the `Resource` object, like converting the content from markdown to HTML (currently `ResourceLoader` is responsible for this), applying template engine like nunjucks, and changing the extension from `.md` to `.html`.

```ts
interface Format {
  extension: string[],
  loader: ResourceLoader,
  modifiers?: Modifier[],  // array is for multiple modifier
}

interface Modifier {
  modify(resource: Resource): unknown | Promise<void>;
  modifySync(resource: Resource): void;  // If this is not needed, Modifier can be implemented as a simple function
  // addHelper is not needed anymore; you can do it inside Modifier.modify()
}
```

You can implement `Engine` interface which extends `Modifier`, and in this interface you may have helpers, components, or other utilities.

This API fits for your basic concept of 'everything is a plugin'. I like this simple and clear concept, and that is why I choose to use Lume. With this api, now everything is processed by a modifier. `Engine`s are general modifiers. Processors are modifiers `push`ed to `Format.modifiers`, and preprocessors are modifiers `unshift`ed to it.
You can make `Site.loadXXXs`, `Site.process`, and `Site.preprocess` to be aliased to new API for managing site modifiers, if backward compatibility matters. The new APIs may be like a pair of `Site.modifiers.append(extensions: string[], modifier)` and `Site.modifiers.prepend(...)`.

**Comment by oscarotero** [comment]
@aiotter thanks for your suggestions. They looks great, and clearly this is the direction I want to take: simple and easy code providing high flexibility and freedom.

The behavior of processors and preprocessors is a bit different to engines because they must be executed in the same order they where declared. For example, if you want to use a processor to transform css (like postcss) and other to minify the css code, the first processor must run **all pages** before start running the second processor. This is why they are saved in a different way because order matters here. In the render engines, the order doesn't no matter (unless you want to specify a specific order with `renderOrder` variable).

The idea of moving the different treatment of html pages and asset pages looks fine, but the difference is more than just replace the extension with `.html`:
- Depending of the configuration (`prettyUrls`), the HTML pages can simply replace the extension to `.html`, or add the `/index.html` suffix.
- The HTML pages also detects the `date` variable from the filename (like `2020-01-03_filename.md`) and remove this part to generate the final name. This behavior is not applied to assets (although it could).

I want to think about this before make more changes because I don't want to break backward compatibility. I've created a new class `Formats` to replace the old `Extensions` and extended the `Format` interface with all values needed by loaders and engines, so now the extensions are centralized in one place:

https://github.com/lumeland/lume/blob/5228c8a5786b18a08f4442fb9a5f5ffd00927513/core/formats.ts#L7-L16

I think this is enough for now but will continue working to make Lume more simple and flexible, like you are suggesting in next versions. Thanks!

**Pull request merged**
