### PR TITLE
Update search operators

### PR DESCRIPTION
**Pull request by valtlai**
Changes the search operators as follows:
 - `~=` to `*=` (matching CSS)
 - `ALL` to `&=`
 - `SOME` to `|=`

### CODE REVIEW

**Comment by oscarotero** [comment]
I like it and understand the logic:
- `~= `to `*=`: Obviously.
- `ALL` TO `&=`: `&` is like AND operator, so makes sense because we want all values are present
- `SOME` TO `|=`: `|` is like OR operator, so makes sense because only on match is required.

**Comment by oscarotero** [comment]
Note that any condition without operator is interpreted as `tags &=`. So this new syntax should be updated also here: https://github.com/lumeland/lume/blob/ff5b9d63852311e43ca652a04a56e20cd70be76b/helpers/search.js#L81-L86

**Comment by valtlai** [comment]
Updated that and also a regex (at the same time, I also deleted the unnecessary escapes inside the character classes).

**Comment by oscarotero** [comment]
Look good to me. Thanks!

**Pull request merged**
