### PR TITLE
Typescript code conversion

### PR DESCRIPTION
**Pull request by oscarotero**
By popular request, I'm trying to convert Lume to Typescript. I'm not an expert and I'd like to check also how this can affect to performance (the initial checking seems slower).
If anyone want to help here, it will be really appreciated.

### CODE REVIEW

**Comment by shah** [comment]
@oscarotero TypeScript startup speed will _definitely_ be slower but execution speed should be the same or negligible from what I've seen. If you [connect with me on LinkedIn](https://www.linkedin.com/in/shahidshah/) we can coordinate a quick call or two to discuss where my team and I might be able to help. I've got a lot of Deno-specific TypeScript under my belt and we are heavy users of Hugo with lots of opinionated views about static sites so joining forces makes sense.

**Comment by shah** [comment]
It looks like you're making good progress here @oscarotero, nice work. If you're interested in a collaborative code review for some comments for stronger type-safety let me know and we can schedule some time to chat via Skype or Discord audio/video. My suggestions will be opinionated and worth a "live" conversation if you think that's useful. I could also show you my latest code where I've added TypeScript in my content to see if that might help inform some of your changes.

**Comment by oscarotero** [comment]
@shah There's still much work to do and I'm learning Typescript at the same time, but yes, I've made some progress.
Code review would be great but it's too early right now. Feel free to make PR if you see something that could be improved.

**Comment by oscarotero** [comment]
@shah Ok, I need help here. There are many typescript errors that I don't know how to fix.

If you want to take a look, I'd really appreciate it.

I didn't ported yet the `cli` folder because I probably use an external library to simplify the code, like [denomander](https://deno.land/x/denomander@0.8.2) or [cliffy](https://deno.land/x/cliffy@v0.19.2)

**Comment by shah** [comment]
@oscarotero sorry, looks like I missed your message from last week. Do you want to try a collaborative session via screen share to show me where you're seeing errors and we can review together? To coordinate drop me an email since I'm part of many GitHub projects and could miss it coming just through GH.

**Comment by oscarotero** [comment]
@shah Don't worry. Finally I've managed to convert the library to Typescript progressively, so this branch will be removed.

The collaborative session would be great but I'll be a bit bussy this next days. If you want, you can take a look to `master` branch, specially if you search for `// @ts-ignore` comments.

**Comment by shah** [comment]
That's fantastic @oscarotero - I look forward to trying out the next release with initial TS implementation!

**Pull request closed without merging**
