### PR TITLE
Add 'brotli' plugin

### PR DESCRIPTION
**Pull request by into-the-v0id**
## Description

Add plugin to compress files with brotli.

Uses https://deno.land/x/brotli@0.1.7

## Related Issues

None

### Check List

- [x] Have you read the
      [CODE OF CONDUCT](https://github.com/lumeland/lume/blob/master/CODE_OF_CONDUCT.md)
- [x] Have you read the document
      [CONTRIBUTING](https://github.com/lumeland/lume/blob/master/CONTRIBUTING.md)
  - [x] One pull request per feature. If you want to do more than one thing,
        send multiple pull request.
  - [x] Write tests.
  - [x] Run deno `fmt` to fix the code format before commit.
  - [x] Document any change in the `CHANGELOG.md`.

### CODE REVIEW

**Comment by oscarotero** [comment]
Thanks!
Some of the comments in https://github.com/lumeland/lume/pull/680 can be applied here.

**Comment by into-the-v0id** [comment]
Note: `CompressionStream` cannot be used for this plugin since it only implements deflate based compression algorithms - so it does not support brotli.

**Comment by into-the-v0id** [comment]
PR updated to use a processor instead of a event.

**Comment by oscarotero** [comment]
thank you!

**Pull request merged**
