### PR TITLE
feat: more visually distinct log for url transformation

### LINKED ISSUE #557: add arrow indicator for url transformation
### Enter your suggestions in details:

It took me embarrassingly long time figuring out which is the original URL and which is the modified one, but making it explicit would be nice.

#### As-is

```
🔥 /index.html /posts/index.tsx
```

#### To-be

```
🔥 /posts/index.tsx -> /index.html 
```

#### Additional notes

I'm willing to open a PR when accepted (since it's tiny)

### PR DESCRIPTION
**Pull request by scarf005**
## Description

| before | after |
| - | - |
|  image | image |

1. extracted url transformation logger formatting into a single function
2. made output url bold to be more visually distinct
3. added arrow to indicate the transformation direction

## Related Issues

resolves #557 

### Check List

- [x] Have you read the
      [CODE OF CONDUCT](https://github.com/lumeland/lume/blob/master/CODE_OF_CONDUCT.md)
- [x] Have you read the document
      [CONTRIBUTING](https://github.com/lumeland/lume/blob/master/CONTRIBUTING.md)
  - [x] One pull request per feature. If you want to do more than one thing,
        send multiple pull request.
  - [ ] Write tests.
  - [x] Run deno `fmt` to fix the code format before commit.
  - [x] Document any change in the `CHANGELOG.md`.

### CODE REVIEW

**Review by kwaa — APPROVED** [review]

**Comment by oscarotero** [comment]
Thanks @scarf005 

After seeing the screenshots, I think the current problem is in the colors. This is how I see the build log in my computer (macos):

imaxe

The page url is white and the source file is gray, so it makes easy to distinguish them.

But in your terminal, the colors are not applied. Do you have any configuration for that? Can you try if other colors are visible?

**Comment by scarf005** [comment]
image

I'm using konsole, and turns out [`dim` isn't supported.](https://stackoverflow.com//questions/19567208/why-is-git-dim-color-option-not-working#answer-19567875)

**Comment by oscarotero** [comment]
Okay, so I propose to modify the `dim` format in Lume and use `gray` instead.
And also remove the `bold` style because it's not needed.
What do you think?

**Comment by oscarotero** [comment]
If it's possible to detect dark/light themes it would be great.
But I guess gray will work fine in both themes.

**Comment by oscarotero** [comment]
Thank you!

**Comment by scarf005** [comment]
er, wait, i think this hasn't been properly removed:

https://github.com/lumeland/lume/blob/e4a98beac4400e1e05fc0a7676bf136e1eabc2c1/core/writer.ts#L146-L149

**Pull request merged**
