### PR TITLE
Add slug to page data

### PR DESCRIPTION
**Pull request by JordanShurmer**
Add the page's "slug" to the page data.

The slug is intended to be the last segment in the url of the page.

### CODE REVIEW

**Comment by oscarotero** [comment]
Why do you need it? (A easier way to get it is with `basename(page.data.url)`).

**Comment by JordanShurmer** [comment]
I've used `slug`  in other frameworks (e.g. 11ty) for various things.

One use I still have is in building out a section's index page. I auto-tag all the pages in directory with the slug of the directory. Then the index-page.njk template can do `search.page(slug)`

**Comment by JordanShurmer** [comment]
I used `page.data.url` at first - seemed like it was always `index` due to the **prettyUrls** logic.

**Comment by oscarotero** [comment]
Note that I've improved the `search` functionality in the last version. Take a look: https://lumeland.github.io/creating-pages/searching/ and now it can search not only by tags but any other field.

To get all pages in a directory, you can do this:

- Add a `_data.yml` file in the directory with any field name that you like to use to select, for example `section: folder-name`
- Then you can search all pages with `search.pages("section=folder-name")`

Another way:

- Simply search pages whose urls starts with something: `search.pages("url^=/folder-name/")`

**Comment by JordanShurmer** [comment]
Ok. I'll take one of those approaches for this.

Feel free to close this PR :)

**Comment by oscarotero** [comment]
Ok, I close this. Anyway, I will think in a way to create permalinks dinamically (for example, with the title slugged)

**Pull request closed without merging**
