### PR TITLE
Allow filename dates to be followed by either an underscore or hyphen

### PR DESCRIPTION
**Pull request by paulrobertlloyd**
## Description

Many (most?) static site generators use a filename format where any date time is separated from the post slug using a hyphen.

[Jekyll](https://jekyllrb.com/docs/posts/#creating-posts):

> To create a post, add a file to your `_posts` directory with the following format:
>
> ```
> YEAR-MONTH-DAY-title.MARKUP
> ```

[Hexo](https://hexo.io/docs/writing#Filename):

> By default, Hexo uses the post title as its filename. You can edit the `new_post_name` setting in `_config.yml` to change the default filename. For example, `:year-:month-:day-:title.md` will prefix filenames with the post creation date. 

[Eleventy](https://www.11ty.dev/docs/dates/):

> If a date key is omitted from the file, we then look for a `YYYY-MM-DD` format anywhere in the file path (even folders).

(I can’t find a specific documented example of the full format but in my own testing, I note that using an underscore between the date and slug doesn’t work, and Eleventy will assume that the date is part of the slug.)

This means that, if you want to port an existing site over to Lume, you will need to update post filenames, which is one more thing to think about.

By parsing filenames using an explicit regex that matches the documented formats (dates `yyyy-mm-dd` or datetimes: `yyyy-mm-dd-hh-ii-ss`), dates can be followed by either an underscore (`_`) or a hyphen (`-`).

### Check List

- [x] Have you read the
      [CODE OF CONDUCT](https://github.com/lumeland/lume/blob/master/CODE_OF_CONDUCT.md)
- [x] Have you read the document
      [CONTRIBUTING](https://github.com/lumeland/lume/blob/master/CONTRIBUTING.md)
  - [x] One pull request per feature. If you want to do more than one thing,
        send multiple pull request.
  - [x] Write tests.
  - [x] Run deno `fmt` to fix the code format before commit.
  - [x] Document any change in the `CHANGELOG.md`.

### CODE REVIEW

**Comment by paulrobertlloyd** [comment]
Hmmm, actually looking at the diff, any time is not included in a post’s date (I misread my local diff, I thought it was improving this and adding the time). May need to tweak this some more…

**Comment by paulrobertlloyd** [comment]
Okay, so have fixed up the regex to not break the tests. Though, thinking about this some more, I’m guessing the original regex is inexact for speed? Will a stricter regex here impact overall build times?

**Comment by oscarotero** [comment]
Initially, Lume supports not only dates but order numbers, so you could name your files as `1_first-article.md`, `2_second-article.md`.
I decided to use underscore to distinguish between the date/order stored in the filename and numbers that can be in the slug (for example `10-rules-of-programming.md` outputs `/10-rules-of-programing/` but `10_rules-of-programming.md` outputs `/rules-of-programing/`).

Ordering is no longer supported, so I think your change make sense. It's unlikely that the slug starts with something that can be intepreted as a date.

About the regex, probably you're right. In fact, the `createDate` function used to create the `Date` object has another regular expression. Perhaps we only need one regex, that can be used to both detect is the date exists and parse it. Something like:

```js
const match = this.src.slug.match(regex);

if (match) {
  const [, year, month, day, hour, minute, second, slug] = match;

  const date = createDate(year, month, day, hour, minute, second);
  this.src.slug = slug
  this.baseData.date = date;
}
```

What do you think? Do you mind to change that?

**Comment by paulrobertlloyd** [comment]
Ah, interesting, wasn’t aware of the ordering background.

I agree, 2 very similar regexes seems wasteful and expensive – that there were 2 is what had me concerned about performance. Consolidating into 1 and providing values directly to the `createDate` function makes a lot of sense.

Will update this PR with such a change. 👍

**Comment by paulrobertlloyd** [comment]
Have update the implementation so that:

* only one regex is needed
* uses named capture groups to help parse the regex
* uses types for values sent to `createDate` function

Also:

* updates one of the file fixtures so that it includes the date separated by a hyphen
* updates resulting snapshots

**Comment by oscarotero** [comment]
Awesome. Thanks!

**Pull request merged**
