### PR TITLE
Output HTML with PHP extension

### PR DESCRIPTION
**Pull request by kouwtkz**
## Description

Add PHP to pages that can be rendered with templates.
Previously only `.html` was applied to layout rendering, so I added `.php`.

## Related Issues

#460

### Check List

- [x] Have you read the
      [CODE OF CONDUCT](https://github.com/lumeland/lume/blob/master/CODE_OF_CONDUCT.md)
- [x] Have you read the document
      [CONTRIBUTING](https://github.com/lumeland/lume/blob/master/CONTRIBUTING.md)
  - [x] One pull request per feature. If you want to do more than one thing,
        send multiple pull request.
  - [x] Write tests.
  - [x] Run deno `fmt` to fix the code format before commit.
  - [x] Document any change in the `CHANGELOG.md`.

### CODE REVIEW

**Comment by kouwtkz** [comment]
> I don't understand. Why do you want to use PHP here? Deno cannot render PHP files.

Because I want to use it as an html template for use with PHP.

As you pointed out, Lume cannot render PHP.
I thought it would be better named "Output HTML with PHP extension", so I'll change the title.

When outputting as HTML, DocType output first hindered PHP execution, so I wanted to add it.
In fact, everything I wanted to solve after adding this was solved, so it was a necessary item for me.
I think it should be one of the options.

**Comment by kouwtkz** [comment]
Also, this execution environment is
HTML Generator: Deno + Lume
Server: Nginx + PHP

Since it is very useful for high-performance HTML output,
I wanted to be able to use PHP extensions in the HTML output using Lume's Layout to keep the site layout consistent.

**Comment by kouwtkz** [comment]
Thank you for understanding.

In my case, the page is a mixture of HTML and PHP, and at present it was enough to process the "layout" in the file specified by "php", but I think the proposal to implement conversion processing as an option is good.
In that case, it might be useful to have an option to specify the extension to output to PHP or HTML if no standard file extension is specified.

Default case: `example.njk -> example.html`

My personal ideal when changing extensions: `Layout extension: [".html", ".php"]`
```
example.njk -> example.php
example.php.njk -> example.php
example/index.njk -> example.php
example.html.njk -> example.html
example/index.html.njk -> example.html
```

Also, if the layout side can handle each extension, it will be more flexible, so it would be better if the extension conversion process is before the line that proposes my this change or "renderedPages.push(page)".

It's my personal opinion, so decide for yourself whether to implement it or not.

**Comment by kouwtkz** [comment]
If you want to implement the option in my ideal form above,
https://github.com/lumeland/lume/blob/01c269b171b893bc96a668bd8d84241b03a45efb/core/filesystem.ts#L82
It seems to work just to apply it here.

Looking at the variables and so on, it seems that it is not possible to obtain which extension to output from the layout side, so it would be personally nice to be able to obtain it.

Looking at the source code, I have a feeling that there are quite a few items that are processed only when it is an html file, and it seems a little difficult to deal with.
Regarding the server etc., I will debug it with my own Nginx, so I will repeat it, but I am personally satisfied if I can just apply the HTML layout with the PHP extension, so my solution may be sufficient.

**Comment by kouwtkz** [comment]
先ほど試しに提案していただいた内容を実行してみました。
```
site.process([".html"], (page) => {
  if (page.data.php) {
    page.data.url = page.outputPath.replace(".html", ".php");
  }
});
```
確かにPHP形式のファイルとして出力されました。

これなら完全なHTMLレイアウトとして機能するので、機能が全て使えて破壊しなくても済むのでその面では良いと思いました。

しかし、これを使用する場合はDocTypeがPHPよりも前に出力されてしまうのが問題です
（今回のissueを提案した一番のきっかけです）
https://github.com/lumeland/lume/blob/01c269b171b893bc96a668bd8d84241b03a45efb/core/renderer.ts#L156

PHPはヘッダーなどでDocTypeの前で処理をする場合があるため、それが非常に不便でした。
ファイルの拡張子の変更という対応を行ったのは視覚的にわかりやすいという点と、DocTypeの自動付与処理を回避するためでもありました。

DocTypeの自動付与を回避できれば、site.processを使用した方式を採用する方向にしてもいいと思います。

**Comment by kouwtkz** [comment]
I tried to do what you suggested earlier.
```
site.process([".html"], (page) => {
   if (page.data.php) {
     page.data.url = page.outputPath.replace(".html", ".php");
   }
});
```
Certainly it was output as a PHP format file.

In this case, it works as a complete HTML layout, so I can use all the functions and don't have to break it, so I thought it was good in that respect.

However, when using this, the problem is that DocType is output before PHP
(This is the main reason why I proposed this issue.)
https://github.com/lumeland/lume/blob/01c269b171b893bc96a668bd8d84241b03a45efb/core/renderer.ts#L156

It was very inconvenient because PHP sometimes processes it before DocType in headers and so on.
The reason we changed the file extension was to make it easier to understand visually and to avoid automatic DocType assignment processing.

If it is possible to avoid the automatic assignment of DocType, I think that you can adopt the method using site.process.
(I posted it without translating it by mistake, so I deleted it and posted it again)

**Comment by oscarotero** [comment]
Ok. Yes, you can use the same processor to remove the doctype:

```js
site.process([".html"], (page) => {
  if (page.data.php) {
    page.data.url = page.outputPath.replace(".html", ".php");
    page.content = page.content.replace("<!DOCTYPE html>\n", "");
  }
});
```

**Comment by kouwtkz** [comment]
> Ok. Yes, you can use the same processor to remove the doctype:
> 
> ```js
> site.process([".html"], (page) => {
>   if (page.data.php) {
>     page.data.url = page.outputPath.replace(".html", ".php");
>     page.content = page.content.replace("<!DOCTYPE html>\n", "");
>   }
> });
> ```

Everything I wanted to achieve has come true.
Great processor.
thank you very much.

Feel free to decline this pull request.
(However, since it seems that other people may have the same problem, I will also quote it to the issue as a knowledge)

**Comment by oscarotero** [comment]
Great! Thanks!

**Pull request closed without merging**
