### PR TITLE
Pre-install TOML Plugin

### PR DESCRIPTION
**Pull request by kwaa**
### Check List

- [x] Have you read the
      [CODE OF CONDUCT](https://github.com/lumeland/lume/blob/master/CODE_OF_CONDUCT.md)
- [x] Have you read the document
      [CONTRIBUTING](https://github.com/lumeland/lume/blob/master/CONTRIBUTING.md)
  - [x] One pull request per feature. If you want to do more than one thing,
        send multiple pull request.
  - [x] Write tests.
  - [x] Run deno `fmt` to fix the code format before commit.
  - [x] Document any change in the `CHANGELOG.md`.

### CODE REVIEW

**Comment by oscarotero** [comment]
Thanks, but I'm not sure this is a good idea.

TOML format is often used for configuration stuff by many deployment services, like `netlify.toml`, `fly.toml`, etc. If this format is enabled by default, all sites using these configuration files will start to have new pages with these files.

I think it's better to have it disabled and only enable it when really need it, (using `site.ignore` if you have files that need to be ignored).

**Comment by kwaa** [comment]
> TOML format is often used for configuration stuff by many deployment services, like `netlify.toml`, `fly.toml`, etc. If this format is enabled by default, all sites using these configuration files will start to have new pages with these files.

yaml and json are also used for configuration of many deployment services (e.g. `vercel.json`, `.github/workflows/*.yml`)

Since there is some difficulty in using deno with these services, I think it should be assumed that anyone using them knows how to set `site.ignore` or `site.src`.

Considering that they are both powered by Deno std, I thought it would be best to make them work out of the box.

**Comment by oscarotero** [comment]
`vercel.json` is not deteted by lume (because the extension to create pages from json on Lume is `.tmpl.json` and github actions are on `.github` folder (ignored by Lume because it starts with a dot.

Anyway, the main problem, right now is that json and yaml are formats enabled by default from the very first version of Lume. Supporting for TOML by default is a good idea, but I would wait to Lume 2.0, that will include some breaking changes.

I'm going to put this PR on hold, and will merge it for Lume 2.0.

**Comment by kwaa** [comment]
OK, pls ping me when Lume 2.0 development starts.

**Comment by oscarotero** [comment]
Sure. Thanks for understanding!

**Comment by oscarotero** [comment]
Merged to v2 branch.

**Pull request merged**
