### PR TITLE
Add plugin for Terser

### PR DESCRIPTION
**Pull request by probins**
As discussed. If you're happy with this, I can write some docs, mainly about the default options and source maps. Obviously, options that use the filesystem won't work.

### CODE REVIEW

**Comment by probins** [comment]
hold on! There seems to be an error in the source map links. Will have to investigate.

**Comment by probins** [comment]
ok. The problem was that I was using `src.path` and not filename in the sourcemap url. The path assumes that cwd is the base address. This will work if the files are deployed at the server base url, but if not (for example, `server/user/...`), then the urls will not be found. Better to use the actual filename.

**Comment by oscarotero** [comment]
It looks good to me.
FYI, 
- All pages and files have the `url` data value, that is generated automatically by lume. So if you want to get the url of a page/file, just need `page.data.url`.
- If the real url is under a subdirectory, you can use the function `site.url(page.data.url)`, that returns the url including the basePath if exists.
The problem of defining the filename with the `file.src` data, is that `file.src` may not be the same as `file.dest`. For example, you could create a js file with a frontmatter to define a different output file:

```js
---
permalink: js/my-script.js
---

// Here's the js code
```

**Comment by probins** [comment]
ok. I've changed `file.src` to `file.dest` as suggested. And have also changed to use std `path.basename` to get the name for the sourcemap link - I think that's easier to read, and as Lume is importing `path.js` anyway, there's no extra overhead.

**Comment by probins** [comment]
fixes #29

**Comment by oscarotero** [comment]
Nice! Thank you!!

**Pull request merged**
